const imageContext = require.context(
  '../Default',
  false,
  /\.(jpg|jpeg|png|webp)$/,
);
const categoryData = imageContext.keys().map(imageContext);

let db = [
  {
    name: 'Egg',
    nameKo: '알',
    code: '000',
    type: [],
    url: '',
  },
  {
    name: 'Bulbasaur',
    nameKo: '이상해씨',
    code: '001',
    type: ['grass', 'poison'],
    url: '',
  },
  {
    name: 'Ivysaur',
    nameKo: '이상해풀',
    code: '002',
    type: ['grass', 'poison'],
    url: '',
  },
  {
    name: 'Venusaur',
    nameKo: '이상해꽃',
    code: '003',
    type: ['grass', 'poison'],
    url: '',
  },
  {
    name: 'Venusaur-Mega',
    nameKo: '메가이상해꽃',
    code: '003-m',
    type: ['grass', 'poison'],
    url: '',
  },
  {
    name: 'Charmander',
    nameKo: '파이리',
    code: '004',
    type: ['fire'],
    url: '',
  },
  {
    name: 'Charmeleon',
    nameKo: '리자드',
    code: '005',
    type: ['fire'],
    url: '',
  },
  {
    name: 'Charizard',
    nameKo: '리자몽',
    code: '006',
    type: ['fire', 'flying'],
    url: '',
  },
  {
    name: 'Charizard-Mega-X',
    nameKo: '메가리자몽-X',
    code: '006-m1',
    type: ['fire', 'dragon'],
    url: '',
  },
  {
    name: 'Charizard-Mega-Y',
    nameKo: '메가리자몽-Y',
    code: '006-m2',
    type: ['fire', 'flying'],
    url: '',
  },
  {
    name: 'Squirtle',
    nameKo: '꼬부기',
    code: '007',
    type: ['water'],
    url: '',
  },
  {
    name: 'Wartortle',
    nameKo: '어니부기',
    code: '008',
    type: ['water'],
    url: '',
  },
  {
    name: 'Blastoise',
    nameKo: '거북왕',
    code: '009',
    type: ['water'],
    url: '',
  },
  {
    name: 'Blastoise-Mega',
    nameKo: '메가거북왕',
    code: '009-m',
    type: ['water'],
    url: '',
  },
  {
    name: 'Caterpie',
    nameKo: '캐터피',
    code: '0010',
    type: ['bug'],
    url: '',
  },
  {
    name: 'Metapod',
    nameKo: '단데기',
    code: '0011',
    type: ['bug'],
    url: '',
  },
  {
    name: 'Butterfree',
    nameKo: '버터풀',
    code: '0012',
    type: ['bug', 'flying'],
    url: '',
  },
  {
    name: 'Weedle',
    nameKo: '뿔충이',
    code: '0013',
    type: ['bug', 'poison'],
    url: '',
  },
  {
    name: 'Kakuna',
    nameKo: '딱충이',
    code: '0014',
    type: ['bug', 'poison'],
    url: '',
  },
  {
    name: 'Beedrill',
    nameKo: '독침붕',
    code: '0015',
    type: ['bug', 'poison'],
    url: '',
  },
  {
    name: 'Beedrill-Mega',
    nameKo: '메가독침붕',
    code: '0015-m',
    type: ['bug', 'poison'],
    url: '',
  },
  {
    name: 'Pidgey',
    nameKo: '구구',
    code: '0016',
    type: ['normal', 'flying'],
    url: '',
  },
  {
    name: 'Pidgeotto',
    nameKo: '피죤',
    code: '0017',
    type: ['normal', 'flying'],
    url: '',
  },
  {
    name: 'Pidgeot',
    nameKo: '피죤투',
    code: '0018',
    type: ['normal', 'flying'],
    url: '',
  },
  {
    name: 'Pidgeot-Mega',
    nameKo: '메가피죤투',
    code: '0018-m',
    type: ['normal', 'flying'],
    url: '',
  },
  {
    name: 'Rattata',
    nameKo: '꼬렛',
    code: '0019',
    type: ['normal'],
    url: '',
  },
  {
    name: 'Rattata-Alola',
    nameKo: '알로라꼬렛',
    code: '0019-Alola',
    type: ['normal', 'dark'],
    url: '',
  },
  {
    name: 'Raticate',
    nameKo: '레트라',
    code: '0020',
    type: ['normal'],
    url: '',
  },
  {
    name: 'Raticate-Alola',
    nameKo: '알로라레트라',
    code: '0020-Alola',
    type: ['normal', 'dark'],
    url: '',
  },
  {
    name: 'Spearow',
    nameKo: '깨비참',
    code: '0021',
    type: ['normal', 'flying'],
    url: '',
  },
  {
    name: 'Fearow',
    nameKo: '깨비드릴조',
    code: '0022',
    type: ['normal', 'flying'],
    url: '',
  },
  {
    name: 'Ekans',
    nameKo: '아보',
    code: '0023',
    type: ['poison'],
    url: '',
  },
  {
    name: 'Arbok',
    nameKo: '아보크',
    code: '0024',
    type: ['poison'],
    url: '',
  },
  {
    name: 'Pikachu',
    nameKo: '피카츄',
    code: '0025',
    type: ['electric'],
    url: '',
  },
  {
    name: 'Pikachu-Original',
    nameKo: '피카츄-오리지널캡',
    code: '0025-Original',
    type: ['electric'],
    url: '',
  },
  {
    name: 'Pikachu-Hoenn',
    nameKo: '피카츄-호연캡',
    code: '0025-Hoenn',
    type: ['electric'],
    url: '',
  },
  {
    name: 'Pikachu-Sinnoh',
    nameKo: '피카츄-신오캡',
    code: '0025-Sinnoh',
    type: ['electric'],
    url: '',
  },
  {
    name: 'Pikachu-Unova',
    nameKo: '피카츄-하나캡',
    code: '0025-Unova',
    type: ['electric'],
    url: '',
  },
  {
    name: 'Pikachu-Kalos',
    nameKo: '피카츄-칼로스캡',
    code: '0025-Kalos',
    type: ['electric'],
    url: '',
  },
  {
    name: 'Pikachu-Alola',
    nameKo: '피카츄-알로라캡',
    code: '0025-Alola',
    type: ['electric'],
    url: '',
  },
  {
    name: 'Pikachu-KimiNiKimeta',
    nameKo: '피카츄-너로정했다캡',
    code: '0025-KimiNiKimeta',
    type: ['electric'],
    url: '',
  },
  {
    name: 'Pikachu-World',
    nameKo: '피카츄-월드캡',
    code: '0025-World',
    type: ['electric'],
    url: '',
  },
  {
    name: 'Raichu',
    nameKo: '라이츄',
    code: '0026',
    type: ['electric'],
    url: '',
  },
  {
    name: 'Raichu-Alola',
    nameKo: '알로라라이츄',
    code: '0026-Alola',
    type: ['electric', 'psychic'],
    url: '',
  },
  {
    name: 'Sandshrew',
    nameKo: '모래두지',
    code: '0027',
    type: ['ground'],
    url: '',
  },
  {
    name: 'Sandshrew-Alola',
    nameKo: '알로라모래두지',
    code: '0027-Alola',
    type: ['ice', 'steel'],
    url: '',
  },
  {
    name: 'Sandslash',
    nameKo: '고지',
    code: '0028',
    type: ['ground'],
    url: '',
  },
  {
    name: 'Sandslash-Alola',
    nameKo: '알로라고지',
    code: '0028-Alola',
    type: ['ice', 'steel'],
    url: '',
  },
  {
    name: 'Nidoran-F',
    nameKo: '니드런♀',
    code: '0029',
    type: ['poison'],
    url: '',
  },
  {
    name: 'Nidorina',
    nameKo: '니드리나',
    code: '0030',
    type: ['poison'],
    url: '',
  },
  {
    name: 'Nidoqueen',
    nameKo: '니드퀸',
    code: '0031',
    type: ['poison', 'ground'],
    url: '',
  },
  {
    name: 'Nidoran-M',
    nameKo: '니드런♂',
    code: '0032',
    type: ['poison'],
    url: '',
  },
  {
    name: 'Nidorino',
    nameKo: '니드리노',
    code: '0033',
    type: ['poison'],
    url: '',
  },
  {
    name: 'Nidoking',
    nameKo: '니드킹',
    code: '0034',
    type: ['poison', 'ground'],
    url: '',
  },
  {
    name: 'Clefairy',
    nameKo: '삐삐',
    code: '0035',
    type: ['fairy'],
    url: '',
  },
  {
    name: 'Clefable',
    nameKo: '픽시',
    code: '0036',
    type: ['fairy'],
    url: '',
  },
  {
    name: 'Vulpix',
    nameKo: '식스테일',
    code: '0037',
    type: ['fire'],
    url: '',
  },
  {
    name: 'Vulpix-Alola',
    nameKo: '알로라식스테일',
    code: '0037-Alola',
    type: ['ice'],
    url: '',
  },
  {
    name: 'Ninetales',
    nameKo: '나인테일',
    code: '0038',
    type: ['fire'],
    url: '',
  },
  {
    name: 'Ninetales-Alola',
    nameKo: '알로라나인테일',
    code: '0038-Alola',
    type: ['ice', 'fairy'],
    url: '',
  },
  {
    name: 'Jigglypuff',
    nameKo: '푸린',
    code: '0039',
    type: ['normal', 'fairy'],
    url: '',
  },
  {
    name: 'Wigglytuff',
    nameKo: '푸크린',
    code: '0040',
    type: ['normal', 'fairy'],
    url: '',
  },
  {
    name: 'Zubat',
    nameKo: '주뱃',
    code: '0041',
    type: ['poison', 'flying'],
    url: '',
  },
  {
    name: 'Golbat',
    nameKo: '골뱃',
    code: '0042',
    type: ['poison', 'flying'],
    url: '',
  },
  {
    name: 'Oddish',
    nameKo: '뚜벅쵸',
    code: '0043',
    type: ['poison', 'grass'],
    url: '',
  },
  {
    name: 'Gloom',
    nameKo: '냄새꼬',
    code: '0044',
    type: ['poison', 'grass'],
    url: '',
  },
  {
    name: 'Vileplume',
    nameKo: '라플레시아',
    code: '0045',
    type: ['poison', 'grass'],
    url: '',
  },
  {
    name: 'Paras',
    nameKo: '파라스',
    code: '0046',
    type: ['bug', 'grass'],
    url: '',
  },
  {
    name: 'Parasect',
    nameKo: '파라섹트',
    code: '0047',
    type: ['bug', 'grass'],
    url: '',
  },
  {
    name: 'Venonat',
    nameKo: '콘팡',
    code: '0048',
    type: ['poison', 'bug'],
    url: '',
  },
  {
    name: 'Venomoth',
    nameKo: '도나리',
    code: '0049',
    type: ['poison', 'bug'],
    url: '',
  },
  {
    name: 'Diglett',
    nameKo: '디그다',
    code: '0050',
    type: ['ground'],
    url: '',
  },
  {
    name: 'Diglett-Alola',
    nameKo: '알로라디그다',
    code: '0050-Alola',
    type: ['ground', 'steel'],
    url: '',
  },
  {
    name: 'Dugtrio',
    nameKo: '닥트리오',
    code: '0051',
    type: ['ground'],
    url: '',
  },
  {
    name: 'Dugtrio-Alola',
    nameKo: '알로라닥트리오',
    code: '0051-Alola',
    type: ['ground', 'steel'],
    url: '',
  },
  {
    name: 'Meowth',
    nameKo: '나옹',
    code: '0052',
    type: ['normal'],
    url: '',
  },
  {
    name: 'Meowth-Alola',
    nameKo: '알로라나옹',
    code: '0052-Alola',
    type: ['dark'],
    url: '',
  },
  {
    name: 'Meowth-Galar',
    nameKo: '가라르나옹',
    code: '0052-Galar',
    type: ['steel'],
    url: '',
  },
  {
    name: 'Persian',
    nameKo: '페르시온',
    code: '0053',
    type: ['normal'],
    url: '',
  },
  {
    name: 'Persian-Alola',
    nameKo: '알로라페르시온',
    code: '0053-Alola',
    type: ['dark'],
    url: '',
  },
  {
    name: 'Psyduck',
    nameKo: '고라파덕',
    code: '0054',
    type: ['water'],
    url: '',
  },
  {
    name: 'Golduck',
    nameKo: '골덕',
    code: '0055',
    type: ['water'],
    url: '',
  },
  {
    name: 'Mankey',
    nameKo: '망키',
    code: '0056',
    type: ['fighting'],
    url: '',
  },
  {
    name: 'Primeape',
    nameKo: '성원숭',
    code: '0057',
    type: ['fighting'],
    url: '',
  },
  {
    name: 'Growlithe',
    nameKo: '가디',
    code: '0058',
    type: ['fire'],
    url: '',
  },
  {
    name: 'Growlithe-Hisui',
    nameKo: '히스이가디',
    code: '0058-Hisui',
    type: ['fire', 'rock'],
    url: '',
  },
  {
    name: 'Arcanine',
    nameKo: '윈디',
    code: '0059',
    type: ['fire'],
    url: '',
  },
  {
    name: 'Arcanine-Hisui',
    nameKo: '히스이윈디',
    code: '0059-Hisui',
    type: ['fire', 'rock'],
    url: '',
  },
  {
    name: 'Poliwag',
    nameKo: '발챙이',
    code: '0060',
    type: ['water'],
    url: '',
  },
  {
    name: 'Poliwhirl',
    nameKo: '슈륙챙이',
    code: '0061',
    type: ['water'],
    url: '',
  },
  {
    name: 'Poliwrath',
    nameKo: '강챙이',
    code: '0062',
    type: ['water', 'fighting'],
    url: '',
  },
  {
    name: 'Abra',
    nameKo: '케이시',
    code: '0063',
    type: ['psychic'],
    url: '',
  },
  {
    name: 'Kadabra',
    nameKo: '윤겔라',
    code: '0064',
    type: ['psychic'],
    url: '',
  },
  {
    name: 'Alakazam',
    nameKo: '후딘',
    code: '0065',
    type: ['psychic'],
    url: '',
  },
  {
    name: 'Alakazam-Mega',
    nameKo: '메가후딘',
    code: '0065-m',
    type: ['psychic'],
    url: '',
  },
  {
    name: 'Machop',
    nameKo: '알통몬',
    code: '0066',
    type: ['fighting'],
    url: '',
  },
  {
    name: 'Machoke',
    nameKo: '근육몬',
    code: '0067',
    type: ['fighting'],
    url: '',
  },
  {
    name: 'Machamp',
    nameKo: '괴력몬',
    code: '0068',
    type: ['fighting'],
    url: '',
  },
  {
    name: 'Bellsprout',
    nameKo: '모다피',
    code: '0069',
    type: ['grass', 'poison'],
    url: '',
  },
  {
    name: 'Weepinbell',
    nameKo: '우츠동',
    code: '0070',
    type: ['grass', 'poison'],
    url: '',
  },
  {
    name: 'Victreebel',
    nameKo: '우츠보트',
    code: '0071',
    type: ['grass', 'poison'],
    url: '',
  },
  {
    name: 'Tentacool',
    nameKo: '왕눈해',
    code: '0072',
    type: ['water', 'poison'],
    url: '',
  },
  {
    name: 'Tentacruel',
    nameKo: '독파리',
    code: '0073',
    type: ['water', 'poison'],
    url: '',
  },
  {
    name: 'Geodude',
    nameKo: '꼬마돌',
    code: '0074',
    type: ['rock', 'ground'],
    url: '',
  },
  {
    name: 'Geodude-Alola',
    nameKo: '알로라꼬마돌',
    code: '0075-Alola',
    type: ['rock', 'electric'],
    url: '',
  },
  {
    name: 'Graveler',
    nameKo: '데구리',
    code: '',
    type: ['rock', 'ground'],
    url: '',
  },
  {
    name: 'Graveler-Alola',
    nameKo: '알로라데구리',
    code: '',
    type: ['rock', 'electric'],
    url: '',
  },
  {
    name: 'Golem',
    nameKo: '딱구리',
    code: '',
    type: ['rock', 'ground'],
    url: '',
  },
  {
    name: 'Golem-Alola',
    nameKo: '알로라딱구리',
    code: '',
    type: ['rock', 'electric'],
    url: '',
  },
  {
    name: 'Ponyta',
    nameKo: '포니타',
    code: '',
    type: ['fire'],
    url: '',
  },
  {
    name: 'Ponyta-Galar',
    nameKo: '가라르포니타',
    code: '',
    type: ['psychic'],
    url: '',
  },
  {
    name: 'Rapidash',
    nameKo: '날쌩마',
    code: '',
    type: ['fire'],
    url: '',
  },
  {
    name: 'Rapidash-Galar',
    nameKo: '가라르날쌩마',
    code: '',
    type: ['psychic', 'fairy'],
    url: '',
  },
  {
    name: 'Slowpoke',
    nameKo: '야돈',
    code: '',
    type: ['water', 'psychic'],
    url: '',
  },
  {
    name: 'Slowpoke-Galar',
    nameKo: '가라르야돈',
    code: '',
    type: ['psychic'],
    url: '',
  },
  {
    name: 'Slowbro',
    nameKo: '야도란',
    code: '',
    type: ['water', 'psychic'],
    url: '',
  },
  {
    name: 'Slowbro-Mega',
    nameKo: '메가야도란',
    code: '',
    type: ['water', 'psychic'],
    url: '',
  },
  {
    name: 'Slowbro-Galar',
    nameKo: '가라르야도란',
    code: '',
    type: ['poison', 'psychic'],
    url: '',
  },
  {
    name: 'Magnemite',
    nameKo: '코일',
    code: '',
    type: ['electric', 'steel'],
    url: '',
  },
  {
    name: 'Magneton',
    nameKo: '레어코일',
    code: '',
    type: ['electric', 'steel'],
    url: '',
  },
  {
    name: "Farfetch'd",
    nameKo: '파오리',
    code: '',
    type: ['normal', 'flying'],
    url: '',
  },
  {
    name: "Farfetch'd-Galar",
    nameKo: '가라르파오리',
    code: '',
    type: ['fighting'],
    url: '',
  },
  {
    name: 'Doduo',
    nameKo: '두두',
    code: '',
    type: ['normal', 'flying'],
    url: '',
  },
  {
    name: 'Dodrio',
    nameKo: '두트리오',
    code: '',
    type: ['normal', 'flying'],
    url: '',
  },
  {
    name: 'Seel',
    nameKo: '쥬쥬',
    code: '',
    type: ['water'],
    url: '',
  },
  {
    name: 'Dewgong',
    nameKo: '쥬레곤',
    code: '',
    type: ['water', 'ice'],
    url: '',
  },
  {
    name: 'Grimer',
    nameKo: '질퍽이',
    code: '',
    type: ['poison'],
    url: '',
  },
  {
    name: 'Grimer-Alola',
    nameKo: '알로라질퍽이',
    code: '',
    type: ['poison', 'dark'],
    url: '',
  },
  {
    name: 'Muk',
    nameKo: '질뻐기',
    code: '',
    type: ['poison'],
    url: '',
  },
  {
    name: 'Muk-Alola',
    nameKo: '알로라질뻐기',
    code: '',
    type: ['poison', 'dark'],
    url: '',
  },
  {
    name: 'Shellder',
    nameKo: '셀러',
    code: '',
    type: ['water'],
    url: '',
  },
  {
    name: 'Cloyster',
    nameKo: '파르셀',
    code: '',
    type: ['water', 'ice'],
    url: '',
  },
  {
    name: 'Gastly',
    nameKo: '고오스',
    code: '',
    type: ['ghost', 'poison'],
    url: '',
  },
  {
    name: 'Haunter',
    nameKo: '고우스트',
    code: '',
    type: ['ghost', 'poison'],
    url: '',
  },
  {
    name: 'Genger',
    nameKo: '팬텀',
    code: '',
    type: ['ghost', 'poison'],
    url: '',
  },
  {
    name: 'Genger-Mega',
    nameKo: '메가팬텀',
    code: '',
    type: ['ghost', 'poison'],
    url: '',
  },
  {
    name: 'Onix',
    nameKo: '롱스톤',
    code: '',
    type: ['rock', 'ground'],
    url: '',
  },
  {
    name: 'Drowzee',
    nameKo: '슬리프',
    code: '',
    type: ['psychic'],
    url: '',
  },
  {
    name: 'Hypno',
    nameKo: '슬리퍼',
    code: '',
    type: ['psychic'],
    url: '',
  },
  {
    name: 'Krabby',
    nameKo: '크랩',
    code: '',
    type: ['water'],
    url: '',
  },
  {
    name: 'Kingler',
    nameKo: '킹크랩',
    code: '',
    type: ['water'],
    url: '',
  },
  {
    name: 'Voltorb',
    nameKo: '찌리리공',
    code: '',
    type: ['electric'],
    url: '',
  },
  {
    name: 'Voltorb-Hisui',
    nameKo: '히스이찌리리공',
    code: '',
    type: ['electric', 'grass'],
    url: '',
  },
  {
    name: 'Electrode',
    nameKo: '붐볼',
    code: '',
    type: ['electric'],
    url: '',
  },
  {
    name: 'Electrode-Hisui',
    nameKo: '히스이붐볼',
    code: '',
    type: ['electric', 'grass'],
    url: '',
  },
  {
    name: 'Exeggcute',
    nameKo: '아라리',
    code: '',
    type: ['grass', 'psychic'],
    url: '',
  },
  {
    name: 'Exeggutor',
    nameKo: '나시',
    code: '',
    type: ['grass', 'psychic'],
    url: '',
  },
  {
    name: 'Exeggutor-Alola',
    nameKo: '알로라나시',
    code: '',
    type: ['grass', 'dragon'],
    url: '',
  },
  {
    name: 'Cubone',
    nameKo: '탕구리',
    code: '',
    type: ['ground'],
    url: '',
  },
  {
    name: 'Marowak',
    nameKo: '텅구리',
    code: '',
    type: ['ground'],
    url: '',
  },
  {
    name: 'Marowak-Alola',
    nameKo: '텅구리',
    code: '',
    type: ['fire', 'ghost'],
    url: '',
  },
  {
    name: 'Hitmonlee',
    nameKo: '시라소몬',
    code: '',
    type: ['fighting'],
    url: '',
  },
  {
    name: 'Hitmonchan',
    nameKo: '홍수몬',
    code: '',
    type: ['fighting'],
    url: '',
  },
  {
    name: 'Lickitung',
    nameKo: '내루미',
    code: '',
    type: ['normal'],
    url: '',
  },
  {
    name: 'Koffing',
    nameKo: '또가스',
    code: '',
    type: ['poison'],
    url: '',
  },
  {
    name: 'Koffing',
    nameKo: '또도가스',
    code: '',
    type: ['poison'],
    url: '',
  },
  {
    name: 'Koffing-Galar',
    nameKo: '가라르또도가스',
    code: '',
    type: ['poison', 'fairy'],
    url: '',
  },
  {
    name: 'Rhyhorn',
    nameKo: '뿔카노',
    code: '',
    type: ['ground', 'rock'],
    url: '',
  },
  {
    name: 'Rhydon',
    nameKo: '코뿌리',
    code: '',
    type: ['ground', 'rock'],
    url: '',
  },
  {
    name: 'Chansey',
    nameKo: '럭키',
    code: '',
    type: ['normal'],
    url: '',
  },
  {
    name: 'Tangela',
    nameKo: '덩쿠리',
    code: '',
    type: ['grass'],
    url: '',
  },
  {
    name: 'Kangaskhan',
    nameKo: '캥카',
    code: '',
    type: ['normal'],
    url: '',
  },
  {
    name: 'Kangaskhan-Mega',
    nameKo: '메가캥카',
    code: '',
    type: ['normal'],
    url: '',
  },
  {
    name: 'Horsea',
    nameKo: '쏘드라',
    code: '',
    type: ['water'],
    url: '',
  },
  {
    name: 'Seedra',
    nameKo: '시드라',
    code: '',
    type: ['water'],
    url: '',
  },
  {
    name: 'Goldeen',
    nameKo: '콘치',
    code: '',
    type: ['water'],
    url: '',
  },
  {
    name: 'Seaking',
    nameKo: '왕콘치',
    code: '',
    type: ['water'],
    url: '',
  },
  {
    name: 'Staryu',
    nameKo: '별가사리',
    code: '',
    type: ['water'],
    url: '',
  },
  {
    name: 'Starmie',
    nameKo: '아쿠스타',
    code: '',
    type: ['water', 'psychic'],
    url: '',
  },
  {
    name: 'Mr.Mime',
    nameKo: '마임맨',
    code: '',
    type: ['psychic', 'fairy'],
    url: '',
  },
  {
    name: 'Mr.Mime-Galar',
    nameKo: '가라르마임맨',
    code: '',
    type: ['ice', 'psychic'],
    url: '',
  },
  {
    name: 'Scyther',
    nameKo: '스라크',
    code: '',
    type: ['bug', 'flying'],
    url: '',
  },
  {
    name: 'Jynx',
    nameKo: '루쥬라',
    code: '',
    type: ['ice', 'psychic'],
    url: '',
  },
  {
    name: 'Electabuzz',
    nameKo: '에레브',
    code: '',
    type: ['electric'],
    url: '',
  },
  {
    name: 'Magmar',
    nameKo: '마그마',
    code: '',
    type: ['fire'],
    url: '',
  },

  {
    name: 'Pinsir',
    nameKo: '쁘사이저',
    code: '',
    type: ['bug'],
    url: '',
  },
  {
    name: 'Pinsir-Maga',
    nameKo: '메가쁘사이저',
    code: '',
    type: ['bug', 'flying'],
    url: '',
  },
  {
    name: 'Tauros',
    nameKo: '켄타로스',
    code: '',
    type: ['normal'],
    url: '',
  },
  {
    name: 'Tauros-Paldea-Combat',
    nameKo: '켄타로스(팔데아의모습)-컴뱃종',
    code: '',
    type: ['fighting'],
    url: '',
  },
  {
    name: 'Tauros-Paldea-Blaze',
    nameKo: '켄타로스(팔데아의모습)-블레이즈종',
    code: '',
    type: ['fighting', 'fire'],
    url: '',
  },
  {
    name: 'Tauros-Paldea-Aqua',
    nameKo: '켄타로스(팔데아의모습)-워터종',
    code: '',
    type: ['fighting', 'water'],
    url: '',
  },
  {
    name: 'Magikarp',
    nameKo: '잉어킹',
    code: '',
    type: ['water'],
    url: '',
  },
  {
    name: 'Gyarados',
    nameKo: '갸라도스',
    code: '',
    type: ['water', 'flying'],
    url: '',
  },
  {
    name: 'Gyarados-Mega',
    nameKo: '메가갸라도스',
    code: '',
    type: ['water', 'dark'],
    url: '',
  },
  {
    name: 'Lapras',
    nameKo: '라프라스',
    code: '',
    type: ['water', 'ice'],
    url: '',
  },
  {
    name: 'Ditto',
    nameKo: '메타몽',
    code: '',
    type: ['normal'],
    url: '',
  },
  {
    name: 'Eevee',
    nameKo: '이브이',
    code: '',
    type: ['normal'],
    url: '',
  },
  {
    name: 'Vaporeon',
    nameKo: '샤미드',
    code: '',
    type: ['water'],
    url: '',
  },
  {
    name: 'Jolteon',
    nameKo: '쥬피썬더',
    code: '',
    type: ['electric'],
    url: '',
  },
  {
    name: 'Flareon',
    nameKo: '부스터',
    code: '',
    type: ['fire'],
    url: '',
  },
  {
    name: 'Porygon',
    nameKo: '폴리곤',
    code: '',
    type: ['normal'],
    url: '',
  },
  {
    name: 'Omanyte',
    nameKo: '암나이트',
    code: '',
    type: ['rock', 'water'],
    url: '',
  },
  {
    name: 'Omastar',
    nameKo: '암스타',
    code: '',
    type: ['rock', 'water'],
    url: '',
  },
  {
    name: 'Kabuto',
    nameKo: '투구',
    code: '',
    type: ['rock', 'water'],
    url: '',
  },
  {
    name: 'Kabutops',
    nameKo: '투구푸스',
    code: '',
    type: ['rock', 'water'],
    url: '',
  },
  {
    name: 'Aerodactyl',
    nameKo: '프테라',
    code: '',
    type: ['rock', 'flying'],
    url: '',
  },
  {
    name: 'Aerodactyl-Mega',
    nameKo: '메가프테라',
    code: '',
    type: ['rock', 'flying'],
    url: '',
  },
  {
    name: 'Snorlax',
    nameKo: '잠만보',
    code: '',
    type: ['normal'],
    url: '',
  },
  {
    name: 'Articuno',
    nameKo: '프리져',
    code: '',
    type: ['ice', 'flying'],
    url: '',
  },
  {
    name: 'Articuno-Galar',
    nameKo: '가라르프리져',
    code: '',
    type: ['psychic', 'flying'],
    url: '',
  },
  {
    name: 'Zapdos',
    nameKo: '썬더',
    code: '',
    type: ['electric', 'flying'],
    url: '',
  },
  {
    name: 'Zapdos-Galar',
    nameKo: '가라르썬더',
    code: '',
    type: ['fighting', 'flying'],
    url: '',
  },
  {
    name: 'Moltres',
    nameKo: '파이어',
    code: '',
    type: ['fire', 'flying'],
    url: '',
  },
  {
    name: 'Zapdos-Galar',
    nameKo: '가라르파이어',
    code: '',
    type: ['dark', 'flying'],
    url: '',
  },
  {
    name: 'Dratini',
    nameKo: '미뇽',
    code: '',
    type: ['dragon'],
    url: '',
  },
  {
    name: 'Dragonair',
    nameKo: '신뇽',
    code: '',
    type: ['dragon'],
    url: '',
  },
  {
    name: 'Dragonite',
    nameKo: '망나뇽',
    code: '',
    type: ['dragon', 'flying'],
    url: '',
  },
  {
    name: 'Mewtwo',
    nameKo: '뮤츠',
    code: '',
    type: ['psychic'],
    url: '',
  },
  {
    name: 'Mewtwo-Maga-X',
    nameKo: '메가뮤츠X',
    code: '',
    type: ['psychic', 'fighting'],
    url: '',
  },
  {
    name: 'Mewtwo-Maga-Y',
    nameKo: '메가뮤츠Y',
    code: '',
    type: ['psychic'],
    url: '',
  },
  {
    name: 'Mew',
    nameKo: '뮤',
    code: '',
    type: ['psychic'],
    url: '',
  },
  {
    name: 'Chikorita',
    nameKo: '치코리타',
    code: '',
    type: ['grass'],
    url: '',
  },
  {
    name: 'Bayleaf',
    nameKo: '베이리프',
    code: '',
    type: ['grass'],
    url: '',
  },
  {
    name: 'Meganium',
    nameKo: '메가니움',
    code: '',
    type: ['grass'],
    url: '',
  },
  {
    name: 'Cyndaquill',
    nameKo: '브케인',
    code: '',
    type: ['fire'],
    url: '',
  },
  {
    name: 'Quilava',
    nameKo: '마그케인',
    code: '',
    type: ['fire'],
    url: '',
  },
  {
    name: 'Typhlosion',
    nameKo: '블레이범',
    code: '',
    type: ['fire'],
    url: '',
  },
  {
    name: 'Typhlosion-Hisui',
    nameKo: '히스이블레이범',
    code: '',
    type: ['fire', 'ghost'],
    url: '',
  },
  {
    name: 'Totodile',
    nameKo: '리아코',
    code: '',
    type: ['water'],
    url: '',
  },
  {
    name: 'Croconaw',
    nameKo: '엘리게이',
    code: '',
    type: ['water'],
    url: '',
  },
  {
    name: 'Feraligatr',
    nameKo: '장크로다일',
    code: '',
    type: ['water'],
    url: '',
  },
  {
    name: 'Sentret',
    nameKo: '꼬리선',
    code: '',
    type: ['normal'],
    url: '',
  },
  {
    name: 'Furret',
    nameKo: '다꼬리',
    code: '',
    type: ['normal'],
    url: '',
  },
  {
    name: 'Hoothoot',
    nameKo: '부우부',
    code: '',
    type: ['normal', 'flying'],
    url: '',
  },
  {
    name: 'Noctowl',
    nameKo: '야부엉',
    code: '',
    type: ['normal', 'flying'],
    url: '',
  },
  {
    name: '레디바',
    nameKo: 'Ledyba',
    code: '',
    type: ['bug', 'flying'],
    url: '',
  },
  {
    name: 'Ledian',
    nameKo: '레디안',
    code: '',
    type: ['bug', 'flying'],
    url: '',
  },
  {
    name: 'Spinarak',
    nameKo: '페이검',
    code: '',
    type: ['bug', 'poison'],
    url: '',
  },
  {
    name: 'Ariados',
    nameKo: '아리아도스',
    code: '',
    type: ['bug', 'poison'],
    url: '',
  },
  {
    name: 'Crobat',
    nameKo: '크로뱃',
    code: '',
    type: ['bug', 'flying'],
    url: '',
  },
  {
    name: 'Chinchou',
    nameKo: '초라기',
    code: '',
    type: ['water', 'electric'],
    url: '',
  },
  {
    name: 'Lanturn',
    nameKo: '랜턴',
    code: '',
    type: ['water', 'electric'],
    url: '',
  },
  {
    name: 'Pichu',
    nameKo: '피츄',
    code: '',
    type: ['electric'],
    url: '',
  },
  {
    name: 'Cleffa',
    nameKo: '삐',
    code: '',
    type: ['fairy'],
    url: '',
  },
  {
    name: 'Igglybuff',
    nameKo: '푸푸린',
    code: '',
    type: ['normal', 'fairy'],
    url: '',
  },
  {
    name: 'Togepi',
    nameKo: '토게피',
    code: '',
    type: ['fairy'],
    url: '',
  },
  {
    name: 'Togetic',
    nameKo: '토게틱',
    code: '',
    type: ['fairy', 'flying'],
    url: '',
  },
  {
    name: 'Natu',
    nameKo: '네이티',
    code: '',
    type: ['psychic', 'flying'],
    url: '',
  },
  {
    name: 'Xatu',
    nameKo: '네이티오',
    code: '',
    type: ['psychic', 'flying'],
    url: '',
  },
  {
    name: 'Mareep',
    nameKo: '메리프',
    code: '',
    type: ['electric'],
    url: '',
  },
  {
    name: 'Fleaffy',
    nameKo: '보송송',
    code: '',
    type: ['electric'],
    url: '',
  },
  {
    name: 'Ampharos',
    nameKo: '전룡',
    code: '',
    type: ['electric'],
    url: '',
  },
  {
    name: 'Ampharos-Mega',
    nameKo: '메가전룡',
    code: '',
    type: ['electric', 'dragon'],
    url: '',
  },
  {
    name: 'Bellossom',
    nameKo: '아르코',
    code: '',
    type: ['grass'],
    url: '',
  },
  {
    name: 'Marill',
    nameKo: '마릴',
    code: '',
    type: ['water', 'fairy'],
    url: '',
  },
  {
    name: 'Azumarill',
    nameKo: '마릴리',
    code: '',
    type: ['water', 'fairy'],
    url: '',
  },
  {
    name: 'Sudowoodo',
    nameKo: '꼬지모',
    code: '',
    type: ['rock'],
    url: '',
  },
  {
    name: 'Politoed',
    nameKo: '왕구리',
    code: '',
    type: ['water'],
    url: '',
  },
  {
    name: 'Hoppip',
    nameKo: '통통코',
    code: '',
    type: ['grass', 'flying'],
    url: '',
  },
  {
    name: 'Skiploom',
    nameKo: '두코',
    code: '',
    type: ['grass', 'flying'],
    url: '',
  },
  {
    name: 'Jumpluff',
    nameKo: '솜솜코',
    code: '',
    type: ['grass', 'flying'],
    url: '',
  },
  {
    name: 'Aipom',
    nameKo: '에이팜',
    code: '',
    type: ['normal'],
    url: '',
  },
  {
    name: 'Sunkern',
    nameKo: '해너츠',
    code: '',
    type: ['grass'],
    url: '',
  },
  {
    name: 'Sunflora',
    nameKo: '해루미',
    code: '',
    type: ['grass'],
    url: '',
  },
  {
    name: 'Yanma',
    nameKo: '왕자리',
    code: '',
    type: ['bug', 'flying'],
    url: '',
  },
  {
    name: 'Wooper',
    nameKo: '우파',
    code: '',
    type: ['water', 'ground'],
    url: '',
  },
  {
    name: 'Wooper-Paldea',
    nameKo: '팔데아우파',
    code: '',
    type: ['poison', 'ground'],
    url: '',
  },
  {
    name: 'Quagsire',
    nameKo: '누오',
    code: '',
    type: ['water', 'ground'],
    url: '',
  },
  {
    name: 'Espeon',
    nameKo: '에브이',
    code: '',
    type: ['psychic'],
    url: '',
  },
  {
    name: 'Umbreon',
    nameKo: '블래키',
    code: '',
    type: ['dark'],
    url: '',
  },
  {
    name: 'Murkrow',
    nameKo: '니로우',
    code: '',
    type: ['dark', 'flying'],
    url: '',
  },
  {
    name: 'Slowking',
    nameKo: '야도킹',
    code: '',
    type: ['water', 'psychic'],
    url: '',
  },
  {
    name: 'Slowking-Galar',
    nameKo: '가라르야도킹',
    code: '',
    type: ['poison', 'psychic'],
    url: '',
  },
  {
    name: 'Misdreavus',
    nameKo: '무우마',
    code: '',
    type: ['ghost'],
    url: '',
  },
  {
    name: 'Unown-A',
    nameKo: '안농A',
    code: '',
    type: ['psychic'],
    url: '',
  },
  {
    name: 'Unown-B',
    nameKo: '안농B',
    code: '',
    type: ['psychic'],
    url: '',
  },
  {
    name: 'Unown-C',
    nameKo: '안농C',
    code: '',
    type: ['psychic'],
    url: '',
  },
  {
    name: 'Unown-D',
    nameKo: '안농D',
    code: '',
    type: ['psychic'],
    url: '',
  },
  {
    name: 'Unown-E',
    nameKo: '안농E',
    code: '',
    type: ['psychic'],
    url: '',
  },
  {
    name: 'Unown-F',
    nameKo: '안농F',
    code: '',
    type: ['psychic'],
    url: '',
  },
  {
    name: 'Unown-G',
    nameKo: '안농G',
    code: '',
    type: ['psychic'],
    url: '',
  },
  {
    name: 'Unown-H',
    nameKo: '안농H',
    code: '',
    type: ['psychic'],
    url: '',
  },
  {
    name: 'Unown-I',
    nameKo: '안농I',
    code: '',
    type: ['psychic'],
    url: '',
  },
  {
    name: 'Unown-J',
    nameKo: '안농J',
    code: '',
    type: ['psychic'],
    url: '',
  },

  {
    name: 'Unown-K',
    nameKo: '안농K',
    code: '',
    type: ['psychic'],
    url: '',
  },
  {
    name: 'Unown-L',
    nameKo: '안농L',
    code: '',
    type: ['psychic'],
    url: '',
  },
  {
    name: 'Unown-M',
    nameKo: '안농M',
    code: '',
    type: ['psychic'],
    url: '',
  },
  {
    name: 'Unown-N',
    nameKo: '안농N',
    code: '',
    type: ['psychic'],
    url: '',
  },
  {
    name: 'Unown-O',
    nameKo: '안농O',
    code: '',
    type: ['psychic'],
    url: '',
  },

  {
    name: 'Unown-P',
    nameKo: '안농P',
    code: '',
    type: ['psychic'],
    url: '',
  },
  {
    name: 'Unown-Q',
    nameKo: '안농Q',
    code: '',
    type: ['psychic'],
    url: '',
  },
  {
    name: 'Unown-R',
    nameKo: '안농R',
    code: '',
    type: ['psychic'],
    url: '',
  },
  {
    name: 'Unown-S',
    nameKo: '안농S',
    code: '',
    type: ['psychic'],
    url: '',
  },
  {
    name: 'Unown-T',
    nameKo: '안농T',
    code: '',
    type: ['psychic'],
    url: '',
  },
  {
    name: 'Unown-U',
    nameKo: '안농U',
    code: '',
    type: ['psychic'],
    url: '',
  },
  {
    name: 'Unown-V',
    nameKo: '안농V',
    code: '',
    type: ['psychic'],
    url: '',
  },
  {
    name: 'Unown-W',
    nameKo: '안농W',
    code: '',
    type: ['psychic'],
    url: '',
  },
  {
    name: 'Unown-X',
    nameKo: '안농X',
    code: '',
    type: ['psychic'],
    url: '',
  },
  {
    name: 'Unown-Y',
    nameKo: '안농Y',
    code: '',
    type: ['psychic'],
    url: '',
  },
  {
    name: 'Unown-Z',
    nameKo: '안농Z',
    code: '',
    type: ['psychic'],
    url: '',
  },
  {
    name: 'Unown-!',
    nameKo: '안농!',
    code: '',
    type: ['psychic'],
    url: '',
  },
  {
    name: 'Unown-?',
    nameKo: '안농?',
    code: '',
    type: ['psychic'],
    url: '',
  },
  {
    name: 'Wobuffet',
    nameKo: '마자용',
    code: '',
    type: ['psychic'],
    url: '',
  },
  {
    name: 'Girafarig',
    nameKo: '키링키',
    code: '',
    type: ['normal', 'psychic'],
    url: '',
  },
  {
    name: 'Pineco',
    nameKo: '피콘',
    code: '',
    type: ['bug'],
    url: '',
  },
  {
    name: 'Forretress',
    nameKo: '쏘콘',
    code: '',
    type: ['bug', 'steel'],
    url: '',
  },
  {
    name: 'Dunsparce',
    nameKo: '노고치',
    code: '',
    type: ['normal'],
    url: '',
  },
  {
    name: 'Gligar',
    nameKo: '글라이거',
    code: '',
    type: ['ground', 'flying'],
    url: '',
  },
  {
    name: 'Steelix',
    nameKo: '강철톤',
    code: '',
    type: ['steel', 'ground'],
    url: '',
  },
  {
    name: 'Steelix-Mega',
    nameKo: '메가강철톤',
    code: '',
    type: ['steel', 'ground'],
    url: '',
  },
  {
    name: 'Snubbull',
    nameKo: '블루',
    code: '',
    type: ['fairy'],
    url: '',
  },
  {
    name: 'Granbull',
    nameKo: '그랑블루',
    code: '',
    type: ['fairy'],
    url: '',
  },
  {
    name: 'Qwilfish',
    nameKo: '침바루',
    code: '',
    type: ['water', 'poison'],
    url: '',
  },
  {
    name: 'Qwilfish-Hisui',
    nameKo: '히스이침바루',
    code: '',
    type: ['dark', 'poison'],
    url: '',
  },
  {
    name: 'Scizor',
    nameKo: '핫삼',
    code: '',
    type: ['bug', 'steel'],
    url: '',
  },
  {
    name: 'Scizor-Mega',
    nameKo: '메가핫삼',
    code: '',
    type: ['bug', 'steel'],
    url: '',
  },
  {
    name: 'Shuckle',
    nameKo: '단단지',
    code: '',
    type: ['bug', 'rock'],
    url: '',
  },
  {
    name: 'Heracross',
    nameKo: '헤라크로스',
    code: '',
    type: ['bug', 'fighting'],
    url: '',
  },
  {
    name: 'Heracross-Mega',
    nameKo: '메가헤라크로스',
    code: '',
    type: ['bug', 'fighting'],
    url: '',
  },
  {
    name: 'Sneasel',
    nameKo: '포푸니',
    code: '',
    type: ['dark', 'ice'],
    url: '',
  },
  {
    name: 'Sneasel-Hisui',
    nameKo: '히스이포푸니',
    code: '',
    type: ['fighting', 'poison'],
    url: '',
  },
  {
    name: 'Teddiursa',
    nameKo: '깜지곰',
    code: '',
    type: ['normal'],
    url: '',
  },
  {
    name: 'Ursaring',
    nameKo: '링곰',
    code: '',
    type: ['normal'],
    url: '',
  },
  {
    name: 'Slugma',
    nameKo: '마그마그',
    code: '',
    type: ['fire'],
    url: '',
  },
  {
    name: 'Magcargo',
    nameKo: '마그카르고',
    code: '',
    type: ['fire', 'rock'],
    url: '',
  },
  {
    name: 'Swinub',
    nameKo: '꾸꾸리',
    code: '',
    type: ['ice', 'ground'],
    url: '',
  },
  {
    name: 'Piloswine',
    nameKo: '메꾸리',
    code: '',
    type: ['ice', 'ground'],
    url: '',
  },
  {
    name: 'Corsola',
    nameKo: '코산호',
    code: '',
    type: ['water', 'rock'],
    url: '',
  },
  {
    name: 'Corsola-Galar',
    nameKo: '가라르코산호',
    code: '',
    type: ['ghost'],
    url: '',
  },
  {
    name: 'Remoraid',
    nameKo: '총어',
    code: '',
    type: ['water'],
    url: '',
  },
  {
    name: 'Octillery',
    nameKo: '대포무노',
    code: '',
    type: ['water'],
    url: '',
  },
  {
    name: 'Delibird',
    nameKo: '딜리버드',
    code: '',
    type: ['ice', 'flying'],
    url: '',
  },
  {
    name: 'Mantine',
    nameKo: '만타인',
    code: '',
    type: ['water', 'flying'],
    url: '',
  },
  {
    name: 'Skarmory',
    nameKo: '무장조',
    code: '',
    type: ['steel', 'flying'],
    url: '',
  },
  {
    name: 'Houndour',
    nameKo: '델빌',
    code: '',
    type: ['dark', 'fire'],
    url: '',
  },
  {
    name: 'Houndoom',
    nameKo: '헬가',
    code: '',
    type: ['dark', 'fire'],
    url: '',
  },
  {
    name: 'Houndoom-Mega',
    nameKo: '메가헬가',
    code: '',
    type: ['dark', 'fire'],
    url: '',
  },
  {
    name: 'Kingdra',
    nameKo: '킹드라',
    code: '',
    type: ['water', 'dragon'],
    url: '',
  },
  {
    name: 'Phanpy',
    nameKo: '코코리',
    code: '',
    type: ['ground'],
    url: '',
  },
  {
    name: 'Donphan',
    nameKo: '코리갑',
    code: '',
    type: ['ground'],
    url: '',
  },
  {
    name: 'Porygon2',
    nameKo: '폴리곤2',
    code: '',
    type: ['normal'],
    url: '',
  },
  {
    name: 'Stantler',
    nameKo: '노라키',
    code: '',
    type: ['normal'],
    url: '',
  },
  {
    name: 'Smeargle',
    nameKo: '루브도',
    code: '',
    type: ['normal'],
    url: '',
  },
  {
    name: 'Tyrogue',
    nameKo: '배루키',
    code: '',
    type: ['fighting'],
    url: '',
  },
  {
    name: 'Hitmontop',
    nameKo: '카포에라',
    code: '',
    type: ['fighting'],
    url: '',
  },
  {
    name: 'Smoochum',
    nameKo: '뽀뽀라',
    code: '',
    type: ['ice', 'psychic'],
    url: '',
  },
  {
    name: 'Elekid',
    nameKo: '에레키드',
    code: '',
    type: ['electric'],
    url: '',
  },
  {
    name: 'Magby',
    nameKo: '마그비',
    code: '',
    type: ['fire'],
    url: '',
  },
  {
    name: 'Miltank',
    nameKo: '밀탱크',
    code: '',
    type: ['normal'],
    url: '',
  },
  {
    name: 'Blissey',
    nameKo: '해피너스',
    code: '',
    type: ['normal'],
    url: '',
  },
  {
    name: 'Raikou',
    nameKo: '라이코',
    code: '',
    type: ['electric'],
    url: '',
  },
  {
    name: 'Entei',
    nameKo: '앤테이',
    code: '',
    type: ['fire'],
    url: '',
  },
  {
    name: 'Suicune',
    nameKo: '스이쿤',
    code: '',
    type: ['water'],
    url: '',
  },
  {
    name: 'Larvitar',
    nameKo: '애버라스',
    code: '',
    type: ['rock', 'ground'],
    url: '',
  },
  {
    name: 'Pupitar',
    nameKo: '데기라스',
    code: '',
    type: ['rock', 'ground'],
    url: '',
  },
  {
    name: 'Tyranitar',
    nameKo: '마기라스',
    code: '',
    type: ['rock', 'dark'],
    url: '',
  },
  {
    name: 'Tyranitar-Mega',
    nameKo: '메가마기라스',
    code: '',
    type: ['rock', 'dark'],
    url: '',
  },
  {
    name: 'Lugia',
    nameKo: '루기아',
    code: '',
    type: ['psychic', 'flying'],
    url: '',
  },
  {
    name: 'Ho-Oh',
    nameKo: '칠색조',
    code: '',
    type: ['fire', 'flying'],
    url: '',
  },
  {
    name: 'Celebi',
    nameKo: '세레비',
    code: '',
    type: ['psychic', 'grass'],
    url: '',
  },
  {
    name: 'Treecko',
    nameKo: '나무지기',
    code: '',
    type: ['grass'],
    url: '',
  },
  {
    name: 'Grovyle',
    nameKo: '나무돌이',
    code: '',
    type: ['grass'],
    url: '',
  },
  {
    name: 'Sceptile',
    nameKo: '나무킹',
    code: '',
    type: ['grass'],
    url: '',
  },
  {
    name: 'Sceptile-Mega',
    nameKo: '메가나무킹',
    code: '',
    type: ['grass', 'dragon'],
    url: '',
  },
  {
    name: 'Torchic',
    nameKo: '아차모',
    code: '',
    type: ['fire'],
    url: '',
  },
  {
    name: 'Combusken',
    nameKo: '영치코',
    code: '',
    type: ['fire', 'fighting'],
    url: '',
  },
  {
    name: 'Blaziken',
    nameKo: '번치코',
    code: '',
    type: ['fire', 'fighting'],
    url: '',
  },
  {
    name: 'Blaziken-Mega',
    nameKo: '메가번치코',
    code: '',
    type: ['fire', 'fighting'],
    url: '',
  },
  {
    name: 'Mudkip',
    nameKo: '물짱이',
    code: '',
    type: ['water'],
    url: '',
  },
  {
    name: 'Marshtomp',
    nameKo: '늪짱이',
    code: '',
    type: ['water', 'ground'],
    url: '',
  },
  {
    name: 'Swampert',
    nameKo: '대짱이',
    code: '',
    type: ['water', 'ground'],
    url: '',
  },
  {
    name: 'Swampert-Mega',
    nameKo: '메가대짱이',
    code: '',
    type: ['water', 'ground'],
    url: '',
  },
  {
    name: 'Poochyena',
    nameKo: '포챠나',
    code: '',
    type: ['dark'],
    url: '',
  },
  {
    name: 'Mightyena',
    nameKo: '그라에나',
    code: '',
    type: ['dark'],
    url: '',
  },
  {
    name: 'Zigzagoon',
    nameKo: '지그제구리',
    code: '',
    type: ['normal'],
    url: '',
  },
  {
    name: 'Zigzagoon-Galar',
    nameKo: '가라르지그제구리',
    code: '',
    type: ['normal', 'dark'],
    url: '',
  },
  {
    name: 'Linoone',
    nameKo: '직구리',
    code: '',
    type: ['normal'],
    url: '',
  },
  {
    name: 'Linoone-Galar',
    nameKo: '가라르직구리',
    code: '',
    type: ['normal', 'dark'],
    url: '',
  },
  {
    name: 'Wurmple',
    nameKo: '개무소',
    code: '',
    type: ['bug'],
    url: '',
  },
  {
    name: 'Silcoon',
    nameKo: '실쿤',
    code: '',
    type: ['bug'],
    url: '',
  },
  {
    name: 'Beautifly',
    nameKo: '뷰티플라이',
    code: '',
    type: ['bug', 'flying'],
    url: '',
  },
  {
    name: 'Cascoon',
    nameKo: '카스쿤',
    code: '',
    type: ['bug'],
    url: '',
  },
  {
    name: 'Dustox',
    nameKo: '독케일',
    code: '',
    type: ['bug', 'poison'],
    url: '',
  },
  {
    name: 'Lotad',
    nameKo: '연꽃몬',
    code: '',
    type: ['water', 'grass'],
    url: '',
  },
  {
    name: 'Lombre',
    nameKo: '로토스',
    code: '',
    type: ['water', 'grass'],
    url: '',
  },
  {
    name: 'Ludicolo',
    nameKo: '로파파',
    code: '',
    type: ['water', 'grass'],
    url: '',
  },
  {
    name: 'Seedot',
    nameKo: '도토링',
    code: '',
    type: ['grass'],
    url: '',
  },
  {
    name: 'Nuzleaf',
    nameKo: '잎새코',
    code: '',
    type: ['grass', 'dark'],
    url: '',
  },
  {
    name: 'Shiftry',
    nameKo: '다탱구',
    code: '',
    type: ['grass', 'dark'],
    url: '',
  },
  {
    name: 'Tailow',
    nameKo: '테일로',
    code: '',
    type: ['normal', 'flying'],
    url: '',
  },
  {
    name: 'Swellow',
    nameKo: '스왈로',
    code: '',
    type: ['normal', 'flying'],
    url: '',
  },
  {
    name: 'Wingull',
    nameKo: '갈모매',
    code: '',
    type: ['water', 'flying'],
    url: '',
  },
  {
    name: 'Pelipper',
    nameKo: '패리퍼',
    code: '',
    type: ['water', 'flying'],
    url: '',
  },
  {
    name: 'Ralts',
    nameKo: '랄토스',
    code: '',
    type: ['psychic', 'fairy'],
    url: '',
  },
  {
    name: 'Kirlia',
    nameKo: '킬리아',
    code: '',
    type: ['psychic', 'fairy'],
    url: '',
  },
  {
    name: 'Gardevoir',
    nameKo: '가디안',
    code: '',
    type: ['psychic', 'fairy'],
    url: '',
  },
  {
    name: 'Gardevoir-Mega',
    nameKo: '메가가디안',
    code: '',
    type: ['psychic', 'fairy'],
    url: '',
  },
  {
    name: 'Surskit',
    nameKo: '비구술',
    code: '',
    type: ['bug', 'water'],
    url: '',
  },
  {
    name: 'Masquerain',
    nameKo: '비나방',
    code: '',
    type: ['bug', 'flying'],
    url: '',
  },
  {
    name: 'Shroomish',
    nameKo: '버섯꼬',
    code: '',
    type: ['grass'],
    url: '',
  },
  {
    name: 'Breloom',
    nameKo: '버섯모',
    code: '',
    type: ['grass', 'fighting'],
    url: '',
  },
  {
    name: 'Slakoth',
    nameKo: '게을로',
    code: '',
    type: ['normal'],
    url: '',
  },
  {
    name: 'Vigoroth',
    nameKo: '발바로',
    code: '',
    type: ['normal'],
    url: '',
  },
  {
    name: 'Slaking',
    nameKo: '게을킹',
    code: '',
    type: ['normal'],
    url: '',
  },
  {
    name: 'Nincada',
    nameKo: '토중몬',
    code: '',
    type: ['bug', 'ground'],
    url: '',
  },
  {
    name: 'Ninjask',
    nameKo: '아이스크',
    code: '',
    type: ['bug', 'flying'],
    url: '',
  },
  {
    name: 'Shedinja',
    nameKo: '껍질몬',
    code: '',
    type: ['bug', 'ghost'],
    url: '',
  },
  {
    name: 'Whismur',
    nameKo: '소곤룡',
    code: '',
    type: ['normal'],
    url: '',
  },
  {
    name: 'Loudred',
    nameKo: '노공룡',
    code: '',
    type: ['normal'],
    url: '',
  },
  {
    name: 'Exploud',
    nameKo: '폭음룡',
    code: '',
    type: ['normal'],
    url: '',
  },
  {
    name: 'Makuhita',
    nameKo: '마크탕',
    code: '',
    type: ['fighting'],
    url: '',
  },
  {
    name: 'Hariyama',
    nameKo: '하리뭉',
    code: '',
    type: ['fighting'],
    url: '',
  },
  {
    name: 'Azurill',
    nameKo: '루리리',
    code: '',
    type: ['normal', 'fairy'],
    url: '',
  },
  {
    name: 'Nosepass',
    nameKo: '코코파스',
    code: '',
    type: ['rock'],
    url: '',
  },
  {
    name: 'Skitty',
    nameKo: '에나비',
    code: '',
    type: ['normal'],
    url: '',
  },
  {
    name: 'Delcatty',
    nameKo: '델케티',
    code: '',
    type: ['normal'],
    url: '',
  },
  {
    name: 'Sableye',
    nameKo: '깜까미',
    code: '',
    type: ['dark', 'ghost'],
    url: '',
  },
  {
    name: 'Sableye-Mega',
    nameKo: '메가깜까미',
    code: '',
    type: ['dark', 'ghost'],
    url: '',
  },
  {
    name: 'Mawile',
    nameKo: '입치트',
    code: '',
    type: ['steel', 'fairy'],
    url: '',
  },
  {
    name: 'Mawile-Mega',
    nameKo: '메가입치트',
    code: '',
    type: ['steel', 'fairy'],
    url: '',
  },
  {
    name: 'Aron',
    nameKo: '가보리',
    code: '',
    type: ['steel', 'rock'],
    url: '',
  },
  {
    name: 'Lairon',
    nameKo: '갱도라',
    code: '',
    type: ['steel', 'rock'],
    url: '',
  },
  {
    name: 'Aggron',
    nameKo: '보스로라',
    code: '',
    type: ['steel', 'rock'],
    url: '',
  },
  {
    name: 'Aggron-Mega',
    nameKo: '메가보스로라',
    code: '',
    type: ['steel'],
    url: '',
  },
  {
    name: 'Meditite',
    nameKo: '요가랑',
    code: '',
    type: ['fighting', 'psychic'],
    url: '',
  },
  {
    name: 'Mediticham',
    nameKo: '요가램',
    code: '',
    type: ['fighting', 'psychic'],
    url: '',
  },
  {
    name: 'Mediticham-Mega',
    nameKo: '메가요가램',
    code: '',
    type: ['fighting', 'psychic'],
    url: '',
  },
  {
    name: 'Electrike',
    nameKo: '썬더라이',
    code: '',
    type: ['electric'],
    url: '',
  },
  {
    name: 'Manectirc',
    nameKo: '썬더볼트',
    code: '',
    type: ['electric'],
    url: '',
  },
  {
    name: 'Manectric-Mega',
    nameKo: '메가썬더볼트',
    code: '',
    type: ['electric'],
    url: '',
  },
  {
    name: 'Plusle',
    nameKo: '플러시',
    code: '',
    type: ['electric'],
    url: '',
  },
  {
    name: 'Minun',
    nameKo: '마이농',
    code: '',
    type: ['electric'],
    url: '',
  },
  {
    name: 'Volbeat',
    nameKo: '볼비트',
    code: '',
    type: ['bug'],
    url: '',
  },
  {
    name: 'Illumise',
    nameKo: '네오비트',
    code: '',
    type: ['bug'],
    url: '',
  },
  {
    name: 'Roselia',
    nameKo: '로젤리아',
    code: '',
    type: ['grass', 'posion'],
    url: '',
  },
  {
    name: 'Gulpin',
    nameKo: '꼴깍몬',
    code: '',
    type: ['poison'],
    url: '',
  },
  {
    name: 'Swalot',
    nameKo: '꿀꺽몬',
    code: '',
    type: ['poison'],
    url: '',
  },
  {
    name: 'Carvanha',
    nameKo: '샤프니아',
    code: '',
    type: ['water', 'dark'],
    url: '',
  },
  {
    name: 'Sharpedo',
    nameKo: '샤크니아',
    code: '',
    type: ['water', 'dark'],
    url: '',
  },
  {
    name: 'Sharpedo-Mega',
    nameKo: '메가샤크니아',
    code: '',
    type: ['water', 'dark'],
    url: '',
  },
  {
    name: 'Wailmer',
    nameKo: '고래왕자',
    code: '',
    type: ['water'],
    url: '',
  },
  {
    name: 'Wailord',
    nameKo: '고래왕',
    code: '',
    type: ['water'],
    url: '',
  },
  {
    name: 'Numel',
    nameKo: '둔타',
    code: '',
    type: ['fire', 'ground'],
    url: '',
  },
  {
    name: 'Camerupt',
    nameKo: '폭타',
    code: '',
    type: ['fire', 'ground'],
    url: '',
  },
  {
    name: 'Camerupt-Mega',
    nameKo: '메가폭타',
    code: '',
    type: ['fire', 'ground'],
    url: '',
  },
  {
    name: 'Torkoal',
    nameKo: '코터스',
    code: '',
    type: ['fire'],
    url: '',
  },
  {
    name: 'Spoink',
    nameKo: '피그점프',
    code: '',
    type: ['psychic'],
    url: '',
  },
  {
    name: 'Grumpig',
    nameKo: '피그킹',
    code: '',
    type: ['psychic'],
    url: '',
  },
  {
    name: 'Spinda',
    nameKo: '얼루기',
    code: '',
    type: ['normal'],
    url: '',
  },
  {
    name: 'Trapinch',
    nameKo: '톱치',
    code: '',
    type: ['ground'],
    url: '',
  },
  {
    name: 'Vibrava',
    nameKo: '비브라바',
    code: '',
    type: ['ground', 'dragon'],
    url: '',
  },
  {
    name: 'Flygon',
    nameKo: '플라이곤',
    code: '',
    type: ['ground', 'dragon'],
    url: '',
  },
  {
    name: 'Cacnea',
    nameKo: '선인왕',
    code: '',
    type: ['grass'],
    url: '',
  },
  {
    name: 'Cacturne',
    nameKo: '밤선인',
    code: '',
    type: ['grass', 'dark'],
    url: '',
  },
  {
    name: 'Swablu',
    nameKo: '파비코',
    code: '',
    type: ['normal', 'flying'],
    url: '',
  },
  {
    name: 'Altaria',
    nameKo: '파비코리',
    code: '',
    type: ['dragon', 'flying'],
    url: '',
  },
  {
    name: 'Altaria-Mega',
    nameKo: '메가파비코리',
    code: '',
    type: ['dragon', 'fairy'],
    url: '',
  },
  {
    name: 'Zangoose',
    nameKo: '쟝고',
    code: '',
    type: ['normal'],
    url: '',
  },
  {
    name: 'Seviper',
    nameKo: '세비퍼',
    code: '',
    type: ['poison'],
    url: '',
  },
  {
    name: 'Lunatone',
    nameKo: '루나톤',
    code: '',
    type: ['rock', 'psychic'],
    url: '',
  },
  {
    name: 'Solrock',
    nameKo: '솔록',
    code: '',
    type: ['rock', 'psychic'],
    url: '',
  },
  {
    name: 'Barboach',
    nameKo: '미꾸리',
    code: '',
    type: ['water', 'ground'],
    url: '',
  },
  {
    name: 'Whiscash',
    nameKo: '메깅',
    code: '',
    type: ['water', 'ground'],
    url: '',
  },
  {
    name: 'Corphish',
    nameKo: '가재군',
    code: '',
    type: ['water'],
    url: '',
  },
  {
    name: 'Crawdaunt',
    nameKo: '가재장군',
    code: '',
    type: ['water', 'dark'],
    url: '',
  },
  {
    name: 'Baltoy',
    nameKo: '오뚝군',
    code: '',
    type: ['ground', 'psychic'],
    url: '',
  },
  {
    name: 'Claydol',
    nameKo: '점토도리',
    code: '',
    type: ['ground', 'psychic'],
    url: '',
  },
  {
    name: 'Lileep',
    nameKo: '릴링',
    code: '',
    type: ['rock', 'grass'],
    url: '',
  },
  {
    name: 'Cradily',
    nameKo: '릴리요',
    code: '',
    type: ['rock', 'grass'],
    url: '',
  },
  {
    name: 'Anorith',
    nameKo: '아노딥스',
    code: '',
    type: ['rock', 'bug'],
    url: '',
  },
  {
    name: 'Armaldo',
    nameKo: '아말도',
    code: '',
    type: ['rock', 'bug'],
    url: '',
  },
  {
    name: 'Feebas',
    nameKo: '빈티나',
    code: '',
    type: ['water'],
    url: '',
  },
  {
    name: 'Milotic',
    nameKo: '밀로틱',
    code: '',
    type: ['water'],
    url: '',
  },
  {
    name: 'Castform',
    nameKo: '캐스퐁',
    code: '',
    type: ['normal'],
    url: '',
  },
  {
    name: 'Castform-Sunny',
    nameKo: '캐스퐁-태양',
    code: '',
    type: ['fire'],
    url: '',
  },
  {
    name: 'Castform-Rainny',
    nameKo: '캐스퐁-빗방울',
    code: '',
    type: ['water'],
    url: '',
  },
  {
    name: 'Castform-Snowy',
    nameKo: '캐스퐁-설운',
    code: '',
    type: ['ice'],
    url: '',
  },
  {
    name: 'Kacleon',
    nameKo: '켈리몬',
    code: '',
    type: ['normal'],
    url: '',
  },
  {
    name: 'Shuppet',
    nameKo: '어둠대신',
    code: '',
    type: ['ghost'],
    url: '',
  },
  {
    name: 'Banette',
    nameKo: '다크펫',
    code: '',
    type: ['ghost'],
    url: '',
  },
  {
    name: 'Banette-Mega',
    nameKo: '메가다크펫',
    code: '',
    type: ['ghost'],
    url: '',
  },
  {
    name: 'Duskull',
    nameKo: '해골몽',
    code: '',
    type: ['ghost'],
    url: '',
  },
  {
    name: 'Dusclops',
    nameKo: '미라몽',
    code: '',
    type: ['ghost'],
    url: '',
  },
  {
    name: 'Tropius',
    nameKo: '트로피우스',
    code: '',
    type: ['grass', 'flying'],
    url: '',
  },
  {
    name: 'Chimecho',
    nameKo: '치렁',
    code: '',
    type: ['psychic'],
    url: '',
  },
  {
    name: 'Absol',
    nameKo: '앱솔',
    code: '',
    type: ['dark'],
    url: '',
  },
  {
    name: 'Absol-Mega',
    nameKo: '메가앱솔',
    code: '',
    type: ['dark'],
    url: '',
  },
  {
    name: 'Wynaut',
    nameKo: '마자',
    code: '',
    type: ['psychic'],
    url: '',
  },
  {
    name: 'Snorunt',
    nameKo: '눈꼬마',
    code: '',
    type: ['ice'],
    url: '',
  },
  {
    name: 'Glalie',
    nameKo: '얼음귀신',
    code: '',
    type: ['ice'],
    url: '',
  },
  {
    name: 'Glalie-Mega',
    nameKo: '메가얼음귀신',
    code: '',
    type: ['ice'],
    url: '',
  },
  {
    name: 'Spheal',
    nameKo: '대굴레오',
    code: '',
    type: ['ice', 'water'],
    url: '',
  },
  {
    name: 'Sealeo',
    nameKo: '씨레오',
    code: '',
    type: ['ice', 'water'],
    url: '',
  },
  {
    name: 'Walrein',
    nameKo: '씨카이저',
    code: '',
    type: ['ice', 'water'],
    url: '',
  },
  {
    name: 'Clamperl',
    nameKo: '진주몽',
    code: '',
    type: ['water'],
    url: '',
  },
  {
    name: 'Huntail',
    nameKo: '헌테일',
    code: '',
    type: ['water'],
    url: '',
  },
  {
    name: 'Gorebyss',
    nameKo: '분홍장이',
    code: '',
    type: ['water'],
    url: '',
  },
  {
    name: 'Relicanth',
    nameKo: '시라칸',
    code: '',
    type: ['water', 'rock'],
    url: '',
  },
  {
    name: 'Luvdisc',
    nameKo: '사랑동이',
    code: '',
    type: ['water'],
    url: '',
  },
  {
    name: 'Bagon',
    nameKo: '아공이',
    code: '',
    type: ['dragon'],
    url: '',
  },
  {
    name: 'Shelgon',
    nameKo: '쉘곤',
    code: '',
    type: ['dragon'],
    url: '',
  },
  {
    name: 'Salamence',
    nameKo: '보만다',
    code: '',
    type: ['dragon', 'flying'],
    url: '',
  },
  {
    name: 'Salamence-Mega',
    nameKo: '메가보만다',
    code: '',
    type: ['dragon', 'flying'],
    url: '',
  },
  {
    name: 'Beldum',
    nameKo: '메탕',
    code: '',
    type: ['steel', 'psychic'],
    url: '',
  },
  {
    name: 'Metang',
    nameKo: '메탕구',
    code: '',
    type: ['steel', 'psychic'],
    url: '',
  },
  {
    name: 'Metagross',
    nameKo: '메타그로스',
    code: '',
    type: ['steel', 'psychic'],
    url: '',
  },
  {
    name: 'Metagross-Mega',
    nameKo: '메가메타그로스',
    code: '',
    type: ['steel', 'psychic'],
    url: '',
  },
  {
    name: 'Regirock',
    nameKo: '레지록',
    code: '',
    type: ['rock'],
    url: '',
  },
  {
    name: 'Regice',
    nameKo: '레지아이스',
    code: '',
    type: ['ice'],
    url: '',
  },
  {
    name: 'Registeel',
    nameKo: '레지스틸',
    code: '',
    type: ['steel'],
    url: '',
  },
  {
    name: 'Latias',
    nameKo: '라티아스',
    code: '',
    type: ['dragon', 'psychic'],
    url: '',
  },
  {
    name: 'Latias-Mega',
    nameKo: '메가라티아스',
    code: '',
    type: ['dragon', 'psychic'],
    url: '',
  },
  {
    name: 'Latios',
    nameKo: '라티오스',
    code: '',
    type: ['dragon', 'psychic'],
    url: '',
  },
  {
    name: 'Latios-Mega',
    nameKo: '메가라티오스',
    code: '',
    type: ['dragon', 'psychic'],
    url: '',
  },
  {
    name: 'Kyogre',
    nameKo: '가이오가',
    code: '',
    type: ['water'],
    url: '',
  },
  {
    name: 'Kyogre-Primal',
    nameKo: '원시가이오가',
    code: '',
    type: ['water'],
    url: '',
  },
  {
    name: 'Groudon',
    nameKo: '그란돈',
    code: '',
    type: ['ground'],
    url: '',
  },
  {
    name: 'Groudon-Primal',
    nameKo: '원시그란돈',
    code: '',
    type: ['ground', 'fire'],
    url: '',
  },
  {
    name: 'Rayquaza',
    nameKo: '레쿠쟈',
    code: '',
    type: ['dragon', 'flying'],
    url: '',
  },
  {
    name: 'Rayquaza-Mega',
    nameKo: '메가레쿠쟈',
    code: '',
    type: ['dragon', 'flying'],
    url: '',
  },
  {
    name: 'Jirachi',
    nameKo: '지라치',
    code: '',
    type: ['steel', 'psychic'],
    url: '',
  },
  {
    name: 'Deoxys',
    nameKo: '테오키스',
    code: '',
    type: ['psychic'],
    url: '',
  },
  {
    name: 'Deoxys-Attack',
    nameKo: '테오키스-어택폼',
    code: '',
    type: ['psychic'],
    url: '',
  },
  {
    name: 'Deoxys-Defense',
    nameKo: '테오키스-방어폼',
    code: '',
    type: ['psychic'],
    url: '',
  },
  {
    name: 'Deoxys-Speed',
    nameKo: '테오키스-스피드폼',
    code: '',
    type: ['psychic'],
    url: '',
  },
];

for (let i = 0; i < db.length; i++) {
  db[i].url = categoryData[i];
  db[i].code = imageContext.keys()[i].slice(6, 10);
}

export { db, categoryData };
